[profile.default]
optimizer = true
optimizer_runs = 200
auto_detect_solc = true
src = "contracts"
out = "artifacts"
libs = ["../../node_modules", "node_modules", "lib"]
fs_permissions = [{ access = "read", path = "./artifacts"}, { access = "read-write", path = "./deployments"}, {access = "read-write", path = "./script"}]

[profile.ci]
verbosity = 4

[fuzz]
runs = 400

[fmt]
line_length = 120
multiline_func_header = 'attributes_first'
number_underscore = 'thousands'

[rpc_endpoints]
avalanche = "${RPC_AVALANCHE}"
optimism = "${RPC_OPTIMISM}"
polygon = "${RPC_POLYGON}"
arb_goerli = "${RPC_ARB_GOERLI}"
op_goerli = "${RPC_OP_GOERLI}"
sepolia = "https://ethereum-sepolia.blockpi.network/v1/rpc/public"
arb_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
synapse_sepolia = "https://l2-synapse-sepolia-testnet-1mdqkm651f.t.conduit.xyz"

[etherscan]
avalanche = { key = "${ETHERSCAN_AVALANCHE_KEY}" }
optimism = { key = "${ETHERSCAN_OPTIMISM_KEY}" }
polygon = { key = "${ETHERSCAN_POLYGON_KEY}" }

# See more config options https://github.com/gakonst/foundry/tree/master/config
